<?php

namespace App\Providers;

class SuperMoney extends BaseTransactionProvider
{
    public function setDetails($details)
    {
        parent::setDetails($details); // TODO: Change the autogenerated stub
    }
}
